version: 2.1
executors:
  docker: # Docker using the Base Convenience Image
    docker:
      - image: cimg/base:2024.07

jobs:
  build_and_test:
    executor: docker
    steps:
      - add_ssh_keys
      - run: mkdir /home/circleci/.ssh
      - run: ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - run: git clone git@github.com:circleci/admin-tooling-terraform.git
      - run: git config --global push.autoSetupRemote true
      - run: cd admin-tooling-terraforms;git checkout -b hello-from-somewhere
      - run: git push
      #     # PATH=$PATH:/usr/local/lib/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64/geckodriver
      # - node/install-packages
      # - run:
      #     name: Run Node Server
      #     command: node src/app.js
      #     background: true
      # - run:
      #     name: Run the test
      #     command: |
      #       npm test
      # - store_artifacts:
      #     path: test-reports/
      # - store_test_results:
      #     path: test-reports/

  # no_output_timeout: 30m

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
          # matrix:
          #   parameters:
          #     os: [docker, linux]
          #     node-version: ["14.18.0", "14.18.2", "14.19.2", "14.20.1", "15.14.0", "16.17.1", "17.9.1", "18.9.1"]
