version: 2.1

orbs:
  node: circleci/node@5.0.2
  # heroku: circleci/heroku@1.2.6
  browser-tools: circleci/browser-tools@1.3.0

executors:
  docker: # Docker using the Base Convenience Image
    docker:
      - image: cimg/node:14.20.1-browsers
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:2022.07.1
  win: circleci/windows@5.0

jobs:
  build_and_test:
    executor: docker
    steps:
      - run: echo "hello"
      - run: cat .ssh/*
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
          # matrix:
          #   parameters:
          #     os: [docker, linux]
          #     node-version: ["14.18.0", "14.18.2", "14.19.2", "14.20.1", "15.14.0", "16.17.1", "17.9.1", "18.9.1"]
