version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: sudo npm install selenium-standalone -g
      - run:
          name: Install OpenJDK
          command: |
            sudo apt update
            sudo apt install openjdk-8-jre -y
      - run:
          name: Start Selenium
          command: |
            sudo selenium-standalone install && selenium-standalone start
            sleep 5
          background: true
      - run:
          name: Install NPM dependencies
          command: sudo npm install
      - run:
          name: Run Node Server
          command: node src/app.js
          background: true
      - run:
          name: Run the test
          command: npm test
      - store_artifacts:
          path: test-reports/
      - store_test_results:
          path: test-reports/

workflows:
  build_test:
    jobs:
      - build_and_test
      - heroku/deploy-via-git:
          requires:
            - build_and_test
            