version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run: mkdir ~/junit
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Install NPM dependencies
          command: sudo npm install
      - run:
          name: Run Node Server
          command: node src/app.js
          background: true
      - run:
          name: Run the test
          command: npm test
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_artifacts:
          path: test-reports/
      - store_test_results:
          path: ~/junit

workflows:
  build_test:
    jobs:
      - build_and_test
      - heroku/deploy-via-git:
          requires:
            - build_and_test
            