version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts-browsers # Latest LTS, rather than specifying version
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
        name: Download Selenium
        command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
    - run:
        name: Start Selenium
        command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        background: true
    - run:
        name: Install NPM dependencies
        command: npm install
    - run:
        name: Run NPM
        command: npm run
        background: true
    - run:
        name: Run the test
        command: npm test
    - store_artifacts:
        path: test-reports/
    - store_test_results:
        path: test-reports/

workflows:
  build_test:
    jobs:
      - build_and_test